# Generated by Django 4.2 on 2023-04-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='esta_publico',
            field=models.BooleanField(default=True),
        ),
    ]
