# Generated by Django 4.2 on 2023-04-07 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0002_evento_esta_publico'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresso',
            name='preco',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
